// src/core/report.ts
/**
 * Data quality report — generates a self-contained HTML file summarising
 * every fix applied during a cleaning session.
 *
 * The report includes:
 *   1. Summary table  — file metadata + totals
 *   2. Changes by fix — count per IssueId
 *   3. Before/after   — up to 5 examples per fix type
 */

import type { ParsedFile, CleanResult, CellChange, IssueId } from '../types';

const ISSUE_LABELS: Partial<Record<IssueId, string>> = {
  'empty-rows':       'Empty rows removed',
  'duplicate-rows':   'Duplicate rows removed',
  'whitespace':       'Whitespace fixed',
  'mixed-case':       'Capitalisation normalised',
  'mixed-types':      'Blank equivalents cleared',
  'mixed-dates':      'Dates normalised to ISO 8601',
  'mixed-booleans':   'Boolean values normalised',
  'special-chars':    'Encoding artifacts repaired',
  'currency-numbers': 'Currency formatting stripped',
  'header-issues':    'Headers normalised',
  'contact-formats':  'Contact formats normalised',
  'sparse-columns':   'Sparse columns removed',
  'fuzzy-values':     'Near-duplicate values merged',
  'number-format':    'EU number format normalised',
  'duplicate-columns':'Duplicate columns flagged',
  'find-replace':     'Find & Replace applied',
};

export function generateReport(
  file:            ParsedFile,
  result:          CleanResult,
  displayHeaders:  string[],
  filteredRowCount: number
): string {
  const byReason = new Map<IssueId, CellChange[]>();
  for (const ch of result.changes) {
    if (!byReason.has(ch.reason)) byReason.set(ch.reason, []);
    byReason.get(ch.reason)!.push(ch);
  }

  const changesRows = Array.from(byReason.entries())
    .map(([id, chs]) => {
      const label = ISSUE_LABELS[id] ?? id;
      const examples = chs.slice(0, 5).map(c =>
        `<tr>
           <td>${esc(displayHeaders[c.colIndex] ?? `col_${c.colIndex}`)}</td>
           <td class="before">${esc(c.before)}</td>
           <td class="after">${esc(c.after)}</td>
         </tr>`
      ).join('');
      return `
        <tr class="reason-row">
          <td><strong>${esc(label)}</strong></td>
          <td class="num">${chs.length.toLocaleString()}</td>
        </tr>
        ${examples
          ? `<tr class="examples-row">
               <td colspan="2">
                 <table class="examples">
                   <thead><tr><th>Column</th><th>Before</th><th>After</th></tr></thead>
                   <tbody>${examples}</tbody>
                 </table>
               </td>
             </tr>`
          : ''}`;
    }).join('');

  const removedCount = result.removedRowIndices.length;
  const changedCount = result.changes.length;
  const now          = new Date().toLocaleString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>CSV Doctor Report — ${esc(file.filename)}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 860px; margin: 2rem auto; color: #1e293b; }
  h1   { font-size: 1.4rem; margin-bottom: 0.25rem; }
  .subtitle { color: #64748b; font-size: 0.85rem; margin-bottom: 2rem; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 1.5rem; }
  th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #e2e8f0; font-size: 0.85rem; }
  th { background: #f1f5f9; font-weight: 600; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .reason-row td { background: #f8fafc; font-size: 0.9rem; padding-top: 0.75rem; }
  .examples { margin: 0.5rem 0; }
  .examples th { background: none; font-size: 0.78rem; }
  .examples td { font-size: 0.78rem; font-family: monospace; }
  .before { color: #ef4444; }
  .after  { color: #16a34a; }
  .footer { margin-top: 2rem; font-size: 0.78rem; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 1rem; }
</style>
</head>
<body>
<h1>CSV Doctor — Data Quality Report</h1>
<div class="subtitle">Generated ${now}</div>

<h2>Summary</h2>
<table>
  <tbody>
    <tr><td>File</td><td>${esc(file.filename)}</td></tr>
    <tr><td>Original rows</td><td class="num">${file.rows.length.toLocaleString()}</td></tr>
    <tr><td>Rows after cleaning</td><td class="num">${filteredRowCount.toLocaleString()}</td></tr>
    <tr><td>Rows removed</td><td class="num">${removedCount.toLocaleString()}</td></tr>
    <tr><td>Columns</td><td class="num">${displayHeaders.length.toLocaleString()}</td></tr>
    <tr><td>Cells changed</td><td class="num">${changedCount.toLocaleString()}</td></tr>
    <tr><td>Fixes applied</td><td>${result.appliedFixes.map(id => ISSUE_LABELS[id] ?? id).join(', ')}</td></tr>
  </tbody>
</table>

<h2>Changes by Fix</h2>
<table>
  <thead><tr><th>Fix</th><th class="num">Cells changed</th></tr></thead>
  <tbody>${changesRows || '<tr><td colspan="2">No cell-level changes recorded.</td></tr>'}</tbody>
</table>

<div class="footer">Generated by <a href="https://csv-doctor.dev">CSV Doctor</a></div>
</body>
</html>`;
}

export function downloadReport(html: string, filename: string): void {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 250);
}

export function suggestReportFilename(originalName: string): string {
  const base = originalName.replace(/\.(csv|tsv|txt)$/i, '');
  return `${base}-report.html`;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
